[project]
name = "brainca"
version = "0.3.0"
description = "2D cellular automaton - Brian Silverman's Brain"
readme = "README.md"
license = "BSD-2-Clause"
requires-python = ">=3.11"
dependencies = ["imageio[ffmpeg]>=2.37.3", "numpy", "pygame-ce"]

[project.scripts]
brainca = "brain:run"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]
